[2024-06-18T08:00:01.711+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.weather_data scheduled__2024-06-18T07:45:00+00:00 [queued]>
[2024-06-18T08:00:01.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.weather_data scheduled__2024-06-18T07:45:00+00:00 [queued]>
[2024-06-18T08:00:01.715+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-06-18T08:00:01.720+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): weather_data> on 2024-06-18 07:45:00+00:00
[2024-06-18T08:00:01.722+0000] {standard_task_runner.py:57} INFO - Started process 233 to run task
[2024-06-18T08:00:01.729+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather', 'weather_data', 'scheduled__2024-06-18T07:45:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmplxfou8_3']
[2024-06-18T08:00:01.733+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask weather_data
[2024-06-18T08:00:01.830+0000] {task_command.py:415} INFO - Running <TaskInstance: weather.weather_data scheduled__2024-06-18T07:45:00+00:00 [running]> on host feb0d45f1e24
[2024-06-18T08:00:01.948+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather' AIRFLOW_CTX_TASK_ID='weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:45:00+00:00'
[2024-06-18T08:00:02.006+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('192.168.160.8', 29092)]>: connecting to broker:29092 [('192.168.160.8', 29092) IPv4]
[2024-06-18T08:00:02.006+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-06-18T08:00:02.007+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('192.168.160.8', 29092)]>: Connection complete.
[2024-06-18T08:00:02.114+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-06-18T08:00:02.115+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-06-18T08:00:02.123+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-06-18T08:00:02.125+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2024-06-18T08:00:02.125+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82c8ad00 wrapping '2024-06-18' at 0xffff82d6a5f0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'next_ds', '2024-06-18')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.126+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2024-06-18T08:00:02.126+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82d02080 wrapping '20240618' at 0xffff82d85930 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'next_ds_nodash', '20240618')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.127+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-06-18T08:00:02.127+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.127+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82cf3100 wrapping '2024-06-18' at 0xffff82d6ad70 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'prev_ds', '2024-06-18')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.128+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.128+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82cf3dc0 wrapping '20240618' at 0xffff82d22430 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'prev_ds_nodash', '20240618')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.129+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.129+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-06-18T08:00:02.129+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.130+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82c90340 wrapping '2024-06-19' at 0xffff82d298f0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'tomorrow_ds', '2024-06-19')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.130+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.130+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82c90380 wrapping '20240619' at 0xffff82d1c630 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'tomorrow_ds_nodash', '20240619')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.141+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.141+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82c903c0 wrapping '2024-06-17' at 0xffff82d29b30 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'yesterday_ds', '2024-06-17')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.142+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2024-06-18T08:00:02.142+0000] {secrets_masker.py:277} WARNING - Unable to redact <Proxy at 0xffff82c90140 wrapping '20240617' at 0xffff82d6a930 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'yesterday_ds_nodash', '20240617')>, please report this via <https://github.com/apache/***/issues>. Error was: TypeError: ObjectProxy() missing required argument 'wrapped' (pos 1)
[2024-06-18T08:00:02.118+0000] {kafka_stream.py:62} INFO - {'conf': <airflow.configuration.AirflowConfigParser object at 0xffff887db2e0>, 'dag': <DAG: weather>, 'dag_run': <DagRun weather @ 2024-06-18 07:45:00+00:00: scheduled__2024-06-18T07:45:00+00:00, state:running, queued_at: 2024-06-18 08:00:00.304971+00:00. externally triggered: False>, 'data_interval_end': DateTime(2024, 6, 18, 8, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2024, 6, 18, 7, 45, 0, tzinfo=Timezone('UTC')), 'ds': '2024-06-18', 'ds_nodash': '20240618', 'execution_date': <Proxy at 0xffff82d47940 wrapping DateTime(2024, 6, 18, 7, 45, 0, tzinfo=Timezone('UTC')) at 0xffff82d763b0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'execution_date', DateTime(2024, 6, 18, 7, 45, 0, tzinfo=Timezone('UTC')))>, 'expanded_ti_count': None, 'inlets': [], 'logical_date': DateTime(2024, 6, 18, 7, 45, 0, tzinfo=Timezone('UTC')), 'macros': <module 'airflow.macros' from '/home/airflow/.local/lib/python3.9/site-packages/airflow/macros/__init__.py'>, 'next_ds': <Proxy at 0xffff82c8ad00 wrapping '2024-06-18' at 0xffff82d6a5f0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'next_ds', '2024-06-18')>, 'next_ds_nodash': <Proxy at 0xffff82d02080 wrapping '20240618' at 0xffff82d85930 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'next_ds_nodash', '20240618')>, 'next_execution_date': <Proxy at 0xffff82d02d80 wrapping DateTime(2024, 6, 18, 8, 0, 0, tzinfo=Timezone('UTC')) at 0xffff88507e00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'next_execution_date', DateTime(2024, 6, 18, 8, 0, 0, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {}, 'prev_data_interval_start_success': DateTime(2024, 6, 18, 7, 15, 0, tzinfo=Timezone('UTC')), 'prev_data_interval_end_success': DateTime(2024, 6, 18, 7, 30, 0, tzinfo=Timezone('UTC')), 'prev_ds': <Proxy at 0xffff82cf3100 wrapping '2024-06-18' at 0xffff82d6ad70 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'prev_ds', '2024-06-18')>, 'prev_ds_nodash': <Proxy at 0xffff82cf3dc0 wrapping '20240618' at 0xffff82d22430 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'prev_ds_nodash', '20240618')>, 'prev_execution_date': <Proxy at 0xffff82cf3ec0 wrapping DateTime(2024, 6, 18, 7, 30, 0, tzinfo=Timezone('UTC')) at 0xffff82d14720 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'prev_execution_date', DateTime(2024, 6, 18, 7, 30, 0, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0xffff82d308c0 wrapping DateTime(2024, 6, 18, 7, 15, 0, tzinfo=Timezone('UTC')) at 0xffff82d24450 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'prev_execution_date_success', DateTime(2024, 6, 18, 7, 15, 0, tzinfo=Timezone('UTC')))>, 'prev_start_date_success': DateTime(2024, 6, 18, 7, 30, 0, 829605, tzinfo=Timezone('UTC')), 'run_id': 'scheduled__2024-06-18T07:45:00+00:00', 'task': <Task(PythonOperator): weather_data>, 'task_instance': <TaskInstance: weather.weather_data scheduled__2024-06-18T07:45:00+00:00 [running]>, 'task_instance_key_str': 'weather__weather_data__20240618', 'test_mode': False, 'ti': <TaskInstance: weather.weather_data scheduled__2024-06-18T07:45:00+00:00 [running]>, 'tomorrow_ds': <Proxy at 0xffff82c90340 wrapping '2024-06-19' at 0xffff82d298f0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'tomorrow_ds', '2024-06-19')>, 'tomorrow_ds_nodash': <Proxy at 0xffff82c90380 wrapping '20240619' at 0xffff82d1c630 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'tomorrow_ds_nodash', '20240619')>, 'triggering_dataset_events': {}, 'ts': '2024-06-18T07:45:00+00:00', 'ts_nodash': '20240618T074500', 'ts_nodash_with_tz': '20240618T074500+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0xffff82c903c0 wrapping '2024-06-17' at 0xffff82d29b30 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'yesterday_ds', '2024-06-17')>, 'yesterday_ds_nodash': <Proxy at 0xffff82c90140 wrapping '20240617' at 0xffff82d6a930 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0xffff82d43c10>, 'yesterday_ds_nodash', '20240617')>, 'apikey': '***', 'locations': ['Mumbai', 'Pune', 'Surat', 'Kolkata', 'Jammu', 'Bikaner', 'Indore', 'Chennai', 'Bengaluru', 'Ludhiana'], 'days': 2, 'templates_dict': None}
[2024-06-18T08:03:55.593+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 69, in stream_data
    res = get_data(apikey, location, days)
  File "/opt/airflow/dags/kafka_stream.py", line 15, in get_data
    req = requests.get(url, params=payload)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-06-18T08:03:55.622+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather, task_id=weather_data, execution_date=20240618T074500, start_date=20240618T080001, end_date=20240618T080355
[2024-06-18T08:03:55.652+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task weather_data (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 233)
[2024-06-18T08:03:55.686+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-18T08:03:55.699+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
